blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/frequency403/OpenSourceInitiative.LicenseApi/security/policy
    about: Please report security issues via our Security Policy.
